{{- if .Values.agent.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ng-speech.agent" . }}
  labels:
    {{- include "ng-speech.labels" $ | nindent 4 }}
    component: {{ include "ng-speech.agent" . }}
spec:
  replicas: {{ .Values.agent.replicaCount }}
  selector:
    matchLabels:
      {{- include "ng-speech.selectorLabels" $ | nindent 6 }}
      component: {{ include "ng-speech.agent" . }}
  {{- if .Values.agent.updateStrategy }}
  strategy: {{- toYaml .Values.agent.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      annotations:
      {{- if .Values.agent.podAnnotations }}
        {{- include "common.tplvalues.render" (dict "value" .Values.agent.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/agent/secret.yaml") $ | sha256sum }}
      labels:
        {{- include "ng-speech.selectorLabels" $ | nindent 8 }}
        component: {{ include "ng-speech.agent" . }}
        {{- if .Values.agent.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.agent.podLabels "context" $) | nindent 8 }}
        {{- end }}
    spec:
      {{- if (or .Values.imagePullSecret.enabled .Values.global.imagePullSecrets) }}
      imagePullSecrets:
      {{- if .Values.imagePullSecret.enabled }}
        - name: {{ include "ng-speech.imagePullSecret" .}}
      {{- end }}
      {{- if .Values.global.imagePullSecrets }}
      {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      {{- end }}
      automountServiceAccountToken: {{ .Values.agent.automountServiceAccountToken }}
      terminationGracePeriodSeconds: {{ .Values.agent.terminationGracePeriodSeconds }}
      containers:
        - name: agent
          image: "{{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.imagePullPolicy }}
          ports:
            - name: monitor
              containerPort: 8080
            - name: grpc-api
              containerPort: 8081
          args:
          {{- if .Values.agent.config.sharedWorkspace.enabled }}
            - "--workspace={{ .Values.agent.config.sharedWorkspace.dir }}"
          {{- end }}
            - "--registry-endpoint={{- include "ng-speech.core" $ }}:8081"
            - "--graceful-shutdown-timeout={{ .Values.agent.terminationGracePeriodSeconds }}s"
          {{- range .Values.agent.args }}
            - "{{ . }}"
          {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "ng-speech.agentCfg" $ }}
            {{- if .Values.agent.extraEnvFrom }}
            {{ toYaml .Values.agent.extraEnvFrom | nindent 12 }}
            {{- end }}
          env:
            - name: NG_NODE
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NG_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          {{- if .Values.agent.extraEnvVars }}
          {{- toYaml .Values.agent.extraEnvVars | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.agent.resources | nindent 12 }}
          {{- if .Values.agent.config.sharedWorkspace.enabled }}
          volumeMounts:
            - name: workspace
              mountPath: {{ .Values.agent.config.sharedWorkspace.dir }}
              readOnly: true
          {{- end }}
      volumes:
      {{- if .Values.agent.config.sharedWorkspace.enabled }}
        - name: workspace
          persistentVolumeClaim:
            claimName: {{ include "ng-speech.workspacePvc" $ }}
      {{- end }}
      {{- if .Values.agent.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.agent.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.agent.podAffinityPreset "component" (include "ng-speech.agent" .) "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.agent.podAntiAffinityPreset "component" (include "ng-speech.agent" .) "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.agent.nodeAffinityPreset.type "key" .Values.agent.nodeAffinityPreset.key "values" .Values.agent.nodeAffinityPreset.values) | nindent 10 }}
     {{- end }}
     {{- if .Values.agent.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.agent.nodeSelector "context" $) | nindent 8 }}
     {{- end }}
     {{- if .Values.agent.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.agent.tolerations "context" $) | nindent 8 }}
     {{- end }}
     {{- if .Values.agent.priorityClassName }}
      priorityClassName: {{ .Values.agent.priorityClassName | quote }}
     {{- end }}
     {{- if .Values.agent.schedulerName }}
      schedulerName: {{ .Values.agent.schedulerName }}
     {{- end }}
{{- end }}
