{{- if .Values.agent.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ng-speech.agentCfg" . }}
  labels:
    {{- include "ng-speech.labels" . | nindent 4 }}
stringData:
  NG_REGISTRY_TOKEN: "{{ .Values.core.config.registry.token }}"
  NG_LICENSE_TOKEN: "{{ .Values.core.config.license.token }}"
  NG_GRACEFUL_SHUTDOWN_TIMEOUT: "{{ .Values.core.terminationGracePeriodSeconds }}s"
{{- end }}
