{{- if (gt (len .Values.agent)  0) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ng-speech.agentCfg" . }}
  labels:
    {{- include "ng-speech.labels" . | nindent 4 }}
stringData:
  {{ if .Values.core.config.agent.token }}NG_REGISTRY_TOKEN: "{{ .Values.core.config.agent.token  }}"{{ end }}
  {{ if .Values.core.config.license.token }}NG_LICENSE_TOKEN:"{{ .Values.core.config.license.token }}"{{ end }}
{{- end }}