---

nameOverride: ""
fullnameOverride: ""

imagePullSecrets: [ ]
imagePullPolicy: IfNotPresent

registry:
  domain: harbor.newtoncloud.com
  username: ""
  password: ""
  email: ""

persistence:
  history:
    dir: /var/lib/ng/history
    storageClassName: ""
    storageSize: 20Gi
    accessModes:
      - ReadWriteMany
  workspace:
    dir: /var/lib/ng/workspace
    storageClassName: ""
    storageSize: 80Gi
    accessModes:
      - ReadWriteMany

core:
  image:
    repository: ng/core
  replicas: 1
  license:
    token: ""
  login:
    jwtKey: ""
    jwtAudience: ""
    adminUsername: ngadmin
    adminPassword: ngadmin
  history:
    dir: /var/lib/ng/history
  workspace:
    dir: /var/lib/ng/workspace
  etcd:
    hostPort: etcd:2379
    namespace: ""
    username: ""
    password: ""
  config: |
    etcd:
      {{- toYaml .Values.etcd | nindent 2 }}
    history:
     {{- toYaml .Values.history | nindent 2 }}
    workspace:
      {{- toYaml .Values.workspace | nindent 2 }}
    license:
      {{- toYaml .Values.license | nindent 2 }}
    login:
      {{- toYaml .Values.login | nindent 2 }}
    registry:
       {{- toYaml .Values.registry | nindent 2 }} 
    services: 
      static:
        {{- toYaml (include "ng-v2t.static-services" .) | nindent 4 }}
  structuredConfig: { }
  extraArgs: [ ]
  extraEnv: { }
  nodeSelector: { }
  podAnnotations: { }
  resources: { }
  tolerations: [ ]
  services: [ ]
  terminationGracePeriodSeconds: 600

dashboard:
  pathPrefix: /dashboard
  replicas: 1
  image:
    repository: ng/dashboard
    tag: 0.4.2
  podAnnotations: { }
  resources: { }
  tolerations: [ ]
  nodeSelector: { }

agent:
  image:
    repository: ng/v2t-agent
    tag: 0.4.2
  replicas: 1
  extraArgs: [ ]
  extraEnv: { }
  resources: { }
  tolerations: [ ]
  affinity: { }
  nodeSelector: { }
  podAnnotations: { }
  terminationGracePeriodSeconds: 600

ingress:
  enabled: false
  className: ""
  annotations: { }
  tls:
    enabled: true
    secretName: ""
  traefikIngressRoute:
    enabled: false
    entrypoints:
      - websecure

metrics:
  enabled: false
  serviceMonitor:
    enabled: false

catalog:
  - service: atran-cz-broadcast
    version: "22.0518.160000"
  - service: atran-pl-broadcast
    version: "22.0518.150000"
  - service: atran-sk-broadcast
    version: "22.0518.150000"
  - service: atran-cz-openlex
    version: "22.0607.200000"
  - service: atran-us-openlex
    version: "22.0607.200000"
  - service: atran-sk-openlex
    version: "22.0607.200000"
  - service: vad-default
    version: "22.0607.200000"
  - service: diar-default
    version: "22.0607.200000"
  - service: adsp-vprint-v3
    version: "22.0607.200000"
