---


nameOverride: ""
fullnameOverride: ""

imagePullSecrets: []
imagePullPolicy: IfNotPresent

registry:
  domain: harbor.newtoncloud.com
  username: nobody
  password: node

core:
  name: core
  image:
    repository: ng/core
  replicas: 1
  extraArgs: [ ]
  etcd:
    hostPort: etcd:2379
    namespace: ""
  history:
    dir: /var/lib/ng/history
    persistence:
      enabled: true
      storageClassName: ""
      storageSize: 20Gi
      accessModes:
        - ReadWriteMany
  workspace:
    dir: /var/lib/ng/workspace
    persistence:
      enabled: true
      storageClassName: ""
      storageSize: 80Gi
      accessModes:
        - ReadWriteMany
  license:
    token: ""
  login:
    jwtKey: tc287t60daVXjbRRFsxnK67iiO5tghWF
    adminUsername: ngadmin
    adminPassword: ngadmin

  podAnnotations: { }
  resources: { }
  tolerations: [ ]
  affinity: { }
  nodeSelector: { }

dashboard:
  name: dashboard
  replicas: 1
  image:
    repository: ng/dashboard
    tag: 0.4.2
  podAnnotations: { }
  resources: { }
  tolerations: [ ]
  affinity: { }
  nodeSelector: { }

agents:
  name: agent
  image:
    repository: ng/v2t-agent
    tag: 0.4.2
  replicas: 1
  resources: { }
  tolerations: [ ]
  affinity: { }
  nodeSelector: { }
  podAnnotations: { }


ingress:
  enabled: false
  host: chart-example.local
  className: ""
  annotations: { }

  traefikIngressRoute:
    enabled: false
    entrypoints:
      - websecure
    tls:
      secretName: ""

