
nameOverride: ""
fullnameOverride: ""

imagePullSecrets: [ ]
imagePullPolicy: IfNotPresent

catalog:
  atran-cz-broadcast:
    version: "22.0518.160000"
  atran-pl-broadcast:
    version: "22.0518.160000"
  atran-sk-broadcast:
    version: "22.0518.150000"
  atran-cz-openlex:
    version: "22.0607.200000"
  atran-us-openlex:
    version: "22.0607.200000"
  atran-sk-openlex:
    version: "22.0607.200000"
  vad-default:
    version: "22.0607.200000"
  diar-default:
    version: "22.0607.200000"
  adsp-vprint-v3:
    version: "22.0607.200000"

license:
  token: ""

registry:
  domain: harbor.newtoncloud.com
  username: ""
  password: ""
  email: "user@mail.com"

persistence:
  storageClassName: ""
  history:
    dir: /var/lib/ng/history
    storageClassName: ""
    storageSize: 20Gi
    accessModes:
      - ReadWriteMany
  workspace:
    dir: /var/lib/ng/workspace
    storageClassName: ""
    storageSize: 80Gi
    accessModes:
      - ReadWriteMany

core:
  image:
    repository: ng/core
  replicas: 1
  login:
    jwtKey: pXYhbNALrxAhtSZoql548nePJstH22yvZ6zb
    jwtAudience: ""
    adminUsername: ngadmin
    adminPassword: ngadmin
  history:
    dir: /var/lib/ng/history
  workspace:
    dir: /var/lib/ng/workspace
  etcd:
    hostPort: etcd:2379
    username: ""
    password: ""
  config: |
    etcd:
      {{- toYaml .Values.core.etcd | nindent 2 }}
    history:
      {{- toYaml .Values.core.history | nindent 2 }}
    workspace:
      {{- toYaml .Values.core.workspace | nindent 2 }}
    license:
      {{- toYaml .Values.license | nindent 2 }}
    login:
      {{- toYaml .Values.core.login | nindent 2 }}
    pods:    
      k8s:
        namespace: {{ .Release.Namespace }}
    registry:
      {{- toYaml .Values.registry | nindent 2 }} 
    services:      
      static:
    {{- include "ng-v2t.staticServices" .  | indent 4 }}
  structuredConfig: { }
  terminationGracePeriodSeconds: 600
  extraArgs: [ ]
  extraEnv: { }
  nodeSelector: { }
  podAnnotations: { }
  resources: { }
  tolerations: [ ]

dashboard:
  pathPrefix: /dashboard
  replicas: 1
  image:
    repository: ng/dashboard
    tag: 0.4.2
  podAnnotations: { }
  resources: { }
  tolerations: [ ]
  nodeSelector: { }

agent:
  image:
    repository: ng/v2t-agent
  replicas: 1
  extraArgs: [ ]
  extraEnv: { }
  resources: { }
  tolerations: [ ]
  affinity: { }
  nodeSelector: { }
  podAnnotations: { }
  terminationGracePeriodSeconds: 600

ingress:
  enabled: false
  className: ""
  annotations: { }
  tls:
    enabled: true
    secretName: ""
  traefikIngressRoute:
    enabled: false
    entrypoints:
      - websecure

serviceMonitor:
  enabled: false
