nameOverride: ""
fullnameOverride: ""

imagePullSecrets: [ ]
imagePullPolicy: IfNotPresent

license:
  token: ""

registry:
  domain: harbor.newtoncloud.com
  username: ""
  password: ""
  email: "user@mail.com"

persistence:
  storageClassName: ""
  history:
    dir: /var/lib/ng/history
    storageClassName: ""
    storageSize: 20Gi
    accessModes:
      - ReadWriteMany
  workspace:
    dir: /var/lib/ng/workspace
    storageClassName: ""
    storageSize: 80Gi
    accessModes:
      - ReadWriteMany
core:
  image:
    repository: ng/core
    tag: ""
  replicas: 1
  structuredConfig:
    login:
      jwtKey: pXYhbNALrxAhtSZoql548nePJstH22yvZ6zb
      jwtAudience: ""
      adminUsername: ngadmin
      adminPassword: ngadmin
    history:
      dir: /var/lib/ng/history
    workspace:
      dir: /var/lib/ng/workspace
    etcd:
      username: root
      password: root
  config: |
    etcd:
      hostPort: "{{ template "ng-v2t.etcdHostPort" . }}"   
    license:
      {{- toYaml .Values.license | nindent 2 }}
    pods:    
      k8s:
        namespace: {{ .Release.Namespace }}
    registry:
      {{- toYaml .Values.registry | nindent 2 }} 
    services:      
      static:
    {{- include "ng-v2t.staticServices" .  | indent 4 }}
  terminationGracePeriodSeconds: 600
  extraArgs: [ ]
  extraEnv: { }
  nodeSelector: { }
  podAnnotations: { }
  resources: { }
  tolerations: [ ]

dashboard:
  pathPrefix: /dashboard
  replicas: 1
  image:
    repository: ng/dashboard
    tag: 0.4.2
  podAnnotations: { }
  resources: { }
  tolerations: [ ]
  nodeSelector: { }

agent:
  image:
    repository: ng/v2t-agent
    tag: ""
  replicas: 1
  extraArgs: [ ]
  extraEnv: { }
  resources: { }
  tolerations: [ ]
  affinity: { }
  nodeSelector: { }
  podAnnotations: { }
  terminationGracePeriodSeconds: 600

ingress:
  enabled: false
  className: ""
  annotations: { }
  host: ""
  tls:
    enabled: true
    secretName: ""
  traefikIngressRoute:
    enabled: false
    entrypoints:
      - websecure

serviceMonitor:
  enabled: false

catalog:
  atran-cz-broadcast:
    version: "22.0518.160000"
  atran-pl-broadcast:
    version: "22.0518.160000"
  atran-sk-broadcast:
    version: "22.0518.150000"
  atran-cz-openlex:
    version: "22.0607.200000"
  atran-us-openlex:
    version: "22.0607.200000"
  atran-sk-openlex:
    version: "22.0607.200000"
  vad-default:
    version: "22.0607.200000"
  diar-default:
    version: "22.0607.200000"
  adsp-vprint-v3:
    version: "22.0607.200000"

etcd:
  enabled: true
  localPersistentVolumes:
    enabled: false
    nodes: [ ]
  #    - name: node1
  #      path: /var/lib/my-etcd
  extraEnvVars:
    - name: ETCD_DISABLE_STORE_MEMBER_ID
      value: "true"
    - name: ETCD_DISABLE_PRESTOP
      value: "true"
  image:
    registry: harbor.ite.tul.cz
    repository: library/etcd
    tag: 3.5.4-no-removal
  rbac:
    rootPassword: root
  resources: { }
  persistence:
    storageClass: ""
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 12

