---

nameOverride: ""
fullnameOverride: ""

imagePullSecrets: [ ]
imagePullPolicy: IfNotPresent

registry:
  domain: harbor.newtoncloud.com
  username: ""
  password: ""

persistence:
  history:
    dir: /var/lib/ng/history
    storageClassName: ""
    storageSize: 20Gi
    accessModes:
      - ReadWriteMany
  workspace:
    dir: /var/lib/ng/workspace
    storageClassName: ""
    storageSize: 80Gi
    accessModes:
      - ReadWriteMany

services: []

core:
  name: core
  image:
    repository: ng/core
  replicas: 1
  config:
    etcd:
      hostPort: etcd:2379
      namespace: ""
    history:
      dir: /var/lib/ng/history
    workspace:
      dir: /var/lib/ng/workspace
    license:
      token: ""
    login:
      jwtKey: ""
      adminUsername: ngadmin
      adminPassword: ngadmin
  extraArgs: [ ]
  extraEnv: { }
  nodeSelector: { }
  podAnnotations: { }
  resources: { }
  tolerations: [ ]

dashboard:
  name: dashboard
  pathPrefix: /dashboard
  replicas: 1
  image:
    repository: ng/dashboard
    tag: 0.4.2
  podAnnotations: { }
  resources: { }
  tolerations: [ ]
  nodeSelector: { }

agents:
  name: agent
  image:
    repository: ng/v2t-agent
    tag: 0.4.2
  replicas: 1
  resources: { }
  tolerations: [ ]
  affinity: { }
  nodeSelector: { }
  podAnnotations: { }

ingress:
  enabled: false

  className: ""
  annotations: { }
  tls:
    enabled: true
    secretName: ""
  traefikIngressRoute:
    enabled: false
    entrypoints:
      - websecure

metrics:
  enabled: false
  serviceMonitor:
    enabled: false

catalog:
  - service: atran-cz-broadcast
    version: "22.0518.160000"
  - service: atran-pl-broadcast
    version: "22.0518.150000"
  - service: atran-sk-broadcast
    version: "22.0518.150000"
  - service: atran-cz-openlex
    version: "22.0607.200000"
  - service: atran-us-openlex
    version: "22.0607.200000"
  - service: atran-sk-openlex
    version: "22.0607.200000"
  - service: vad-default
    version: "22.0607.200000"
  - service: diar-default
    version: "22.0607.200000"
  - service: adsp-vprint-v3
    version: "22.0607.200000"
