# Default values for ng-v2t.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


nameOverride: ""
fullnameOverride: ""


imageCredentials:
  registry: quay.io
  username: someone
  password: sillyness
  email: someone@host.com

core:
  image:
    registry: harbor.newtoncloud.com
    repository: nginx
    tag: 0.4.2
  resources: {}
  replicas: 1
  podAnnotations: {}
  debug: false
  extraArgs: []
# extraSecrets

  license: CHANGEME
  s3:
    endpoint: http://${BUCKET_HOST}:${BUCKET_PORT}
    accessKey: ${AWS_SECRET_ACCESS_KEY}
    secretKey: ${AWS_ACCESS_KEY_ID}
    s3ForcePathStyle: true
    insecure: true
    buckets:
      history: history
  etcd:
    endpoint:
    username:
    password:

  service:
    type: ClusterIP
    port: 80

  tolerations: []
  affinity: {}
  nodeSelector: {}

dashboard:
  replicas: 1
  resources: {}


agent:
  name: test
  replicas: 1
  resources: {}
  debug: false
  tolerations: [ ]
  affinity: { }
  nodeSelector: { }
  extraArgs: []
  image:
    registry: harbor.newtoncloud.com
    repository: nginx
    tag: 0.4.2


etcd:
  enabled: false


ceph-bucket:
  enabled: false







ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local


