{{- if .Values.core.enabled }}
{{- if and (eq .Values.core.config.history.type  "fs") .Values.core.config.history.fs.persistence.enabled }}
{{- with .Values.core.config.history.fs.persistence }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "ng-v2t.historyPvc" $ }}"
spec:
  accessModes:
    {{- toYaml .accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .size }}
  storageClassName: "{{ default $.Values.global.storageClass .storageClass }}"
{{- end }}
{{- end }}
{{- end }}
