{{- with .Values.core.config.history.persistence }}
{{- if .enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "ng-speech.historyPvc" $ }}"
  annotations:
    helm.sh/resource-policy: "keep"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .size }}
  storageClassName: "{{ default $.Values.global.storageClass .storageClass }}"
{{- end }}
{{- end }}
