{{ with .Values.persistence.history }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "ng-v2t.historyPvc" $ }}"
spec:
  accessModes:
    {{- toYaml .accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .storageSize }}
  storageClassName: "{{ default $.Values.persistence.storageClassName .storageClassNam }}"
{{ end}}
