{{- if .Values.core.config.history.persistence.enabled }}
{{- with .Values.core.config.sharedWorkspace.persistence }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "ng-speech.historyPvc" $ }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .size }}
  storageClassName: "{{ default $.Values.global.storageClass .storageClass }}"
{{- end }}
{{- end }}
