{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "ng-speech.core" . }}
  labels:
    {{- include "ng-speech.selectorLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "ng-speech.selectorLabels" . | nindent 6 }}
      component: core
  namespaceSelector:
    matchNames:
      - "{{ .Release.Namespace }}"
  endpoints:
    - port: monitor
      path: /metrics
{{- end}}
