apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ng-speech.coreRoleName" . }}
rules:
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get", "watch", "list" ]
