{{- if .Values.core.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ng-speech.coreCfg" . }}
  labels:
    {{- include "ng-speech.labels" . | nindent 4 }}
stringData:
  {{- if eq .Values.core.config.history.type "s3" }}
  {{- with .Values.core.config.history.s3 }}
  NG_HISTORY_S3_ENDPOINT: "{{ .endpoint }}"
  NG_HISTORY_S3_BUCKET: "{{ .bucket }}"
  NG_HISTORY_S3_REGION: "{{ .region }}"
  NG_HISTORY_S3_KEY: "{{ .key }}"
  NG_HISTORY_S3_SECRET: "{{ .secret }}"
  {{- end }}
  {{- end }}
  {{-  if eq .Values.core.config.history.type "fs" }}
  NG_HISTORY_DIR: "{{ .Values.core.config.history.fs.dir }}"
  {{- end }}
  {{- with .Values.core.config.login }}
  NG_LOGIN_JWT_KEY: "{{ .jwt.key }}"
  NG_LOGIN_JWT_TTL: "{{ .jwt.ttl }}"
  NG_LOGIN_ADMIN_USERNAME: "{{ .admin.username }}"
  NG_LOGIN_ADMIN_PASSWORD: "{{ .admin.password }}"
  {{- if .jwt.audience }}
  NG_LOGIN_JWT_AUDIENCE: "{{ .jwt.audience }}"
  {{- end }}
  {{- end }}
  NG_REGISTRY_TOKEN: "{{ .Values.core.config.registry.token }}"
  NG_LICENSE_TOKEN: "{{ .Values.core.config.license.token }}"
  {{- with .Values.core.config.etcd }}
  NG_ETCD_ENDPOINT: "{{ template "ng-speech.etcdEndpoint" $ }}"
  {{- if .username }}
  NG_ETCD_USERNAME: "{{ .username }}"
  {{- end }}
  {{- if .password }}
  NG_ETCD_PASSWORD: "{{ .password }}"
  {{- end}}
  {{- if .namespace }}
  NG_ETCD_NAMESPACE: "{{ .namespace }}"
  {{- end }}
  {{- end }}
  {{- if .Values.core.config.sharedWorkspace.enabled }}
  NG_SHARED_WORKSPACE_DIR: "{{ .Values.core.config.sharedWorkspace.dir }}"
  {{- if .Values.imagePullSecret.enabled }}
  NG_SHARED_WORKSPACE_PULL_USERNAME: {{ .Values.imagePullSecret.username }}
  NG_SHARED_WORKSPACE_PULL_PASSWORD: {{ .Values.imagePullSecret.password }}
  {{- end }}
  {{- end }}
  NG_GRACEFUL_SHUTDOWN_TIMEOUT: "{{ .Values.core.terminationGracePeriodSeconds }}s"
  {{- if .Values.core.config.users }}
  NG_EXTRA_USERS_FILE: "{{ .Values.core.config.usersDir}}/users.yaml"
  {{- end }}
{{- end }}
