
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ng-v2t.coreCfg" . }}
  labels:
    {{- include "ng-v2t.labels" . | nindent 4 }}
stringData:
  core.yaml: |
    {{- (mergeOverwrite (tpl .Values.core.config . | fromYaml) .Values.core.structuredConfig | toYaml) | nindent 4 }}
