
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ng-v2t.coreCfg" . }}
  labels:
    {{- include "ng-v2t.labels" . | nindent 4 }}
stringData:
  core.yaml: |
    {{- (mergeOverwrite (tpl .Values.core.config . | fromYaml) .Values.core.structuredConfig | toYaml) | nindent 4 }}


{{- if not .Values.license.token }}
{{ fail "license token not set" }}
{{- end }}

{{- if not .Values.core.structuredConfig.login.adminPassword }}
{{ fail "login admin password not set" }}
{{- end }}

{{- if not .Values.core.structuredConfig.login.jwtKey }}
{{ fail "login jwtKey not set" }}
{{- end }}

{{- if not .Values.registry.username }}
{{ fail "registry username not set" }}
{{- end }}


{{- if not .Values.registry.password }}
{{ fail "registry password not set" }}
{{- end }}
