apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ng-speech.coreCfg" . }}
  labels:
    {{- include "ng-speech.labels" . | nindent 4 }}
stringData:
  {{- with .Values.core.config.login }}
  {{ if .jwt.key }}NG_LOGIN_JWT_KEY: "{{ .jwt.key  }}"{{- end }}
  NG_LOGIN_JWT_TTL: "{{ .jwt.ttl }}"
  {{ if .admin.username }}NG_LOGIN_ADMIN_USERNAME: "{{ .admin.username }}"{{ end }}
  {{ if .admin.password }}NG_LOGIN_ADMIN_PASSWORD: "{{ .admin.password }}"{{ end }}
  {{ if .jwt.audience }}NG_LOGIN_JWT_AUDIENCE: "{{ .jwt.audience }}"{{ end }}
  {{- end }}
  NG_HISTORY_DIR: "{{ .Values.core.config.history.dir }}"
  {{ if .Values.core.config.agent.token }}NG_AGENT_TOKEN: "{{ .Values.core.config.agent.token  }}"{{ end }}
  NG_AGENT_COUNT: "{{ .Values.core.config.agent.count  }}"
  {{ if .Values.core.config.license.token }}NG_LICENSE_TOKEN: "{{ .Values.core.config.license.token }}"{{ end }}
  {{ if .Values.core.config.sharedWorkspace.persistence.enabled }}NG_SHARED_WORKSPACE_DIR: "{{ .Values.core.config.sharedWorkspace.dir }}"{{ end }}
  NG_GRACEFUL_SHUTDOWN_TIMEOUT: "{{ .Values.core.terminationGracePeriodSeconds }}s"
  {{ if .Values.core.config.users }}NG_EXTRA_USERS_FILE: "{{ .Values.core.config.usersDir}}/users.yaml"{{- end }}
