{{- if .Values.core.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: {{ include "ng-v2t.core" . }}
  labels:
    {{- include "ng-v2t.selectorLabels" . | nindent 4 }}
    component: core
spec:
  ports:
    - name: http
      protocol: TCP
      targetPort: http
      port: 8080
    - name: grpc
      protocol: TCP
      port: 8081
      targetPort: grpc
    - name: monitor
      protocol: TCP
      port: 8082
      targetPort: monitor
  selector:
    {{- include "ng-v2t.selectorLabels" . | nindent 4 }}
    component: core
{{- end }}
