{{- if (and .Values.core.enabled .Values.core.config.sharedWorkspace.enabled) }}
{{- with .Values.core.config.sharedWorkspace.persistence }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "ng-speech.workspacePvc" $ }}"
spec:
  accessModes:
    {{- toYaml .accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .size }}
  storageClassName: "{{ default $.Values.global.storageClass .storageClass }}"
{{- end }}
{{- end }}
