
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "ng-v2t.workspacePvc" $ }}"
spec:
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ $.Values.persistence.workspaceSize }}
  storageClassName: "{{ default .Values.global.storageClass .Values.persistence.storageClass }}"
