{{- if .Values.traefikIngressRoute.enabled }}
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name:  "{{ include "ng-v2t.name" . }}"
spec:
  entryPoints:
    {{- toYaml .Values.traefikIngressRoute.entrypoints | nindent 4 }}
  routes:
    - kind: Rule
      match: {{ include "ng-v2t.traefikOptionalHostRule" . }} PathPrefix(`/`)
      services:
        - name: {{ include "ng-v2t.core" . }}
          port: http
    - kind: Rule
      match: {{ include "ng-v2t.traefikOptionalHostRule" . }} Headers(`Content-Type`,`application/grpc`)
      services:
        - name: {{ include "ng-v2t.core" . }}
          port: grpc
          scheme: h2c
    - kind: Rule
      match: {{ include "ng-v2t.traefikOptionalHostRule" . }} PathPrefix(`/dashboard`)
      services:
        - name: {{ include "ng-v2t.dashboard" . }}
          port: http
  {{- if .Values.traefikIngressRoute.tls.secretName }}
  tls:
    secretName: {{ .Values.traefikIngressRoute.tls.secretName }}
  {{- end }}
{{- end }}
