{{- if .Values.imagePullSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ng-speech.imagePullSecret" . }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "ng-speech.imagePullSecretBody" . }}
{{- end }}
